
package GUI;

import DAOGUI.DAODanhmuc;
import DBConnect.MySQLConnUtils;
import Main.Login;
import GUI.*;
import Frame.*;
import OBJGUI.Danhmuc;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class GUIDanhmuc extends javax.swing.JFrame {
    DAOGUI.DAODanhmuc DAOdanhmuc=new DAODanhmuc();
    public GUIDanhmuc() {
        initComponents();
        setLocationRelativeTo(null);
        loadData();
        r_khac.setActionCommand("Khác");
        r_nam.setActionCommand("Nam");
        r_nu.setActionCommand("Nữ");
        ngayhientai();
    }

    Connection dbConnection = null;
    Statement statement = null;
    public void loadData() {
    // Clear table
    tbl_data.setModel(new DefaultTableModel());
    // Model for Table
    DefaultTableModel model = new DefaultTableModel() {
        public Class<?> getColumnClass(int column) {
            switch (column) {
            case 0:
                return String.class;
            case 1:
                return String.class;
            case 2:
                return String.class;
            case 3:
                return String.class;
            case 4:
                return String.class;
            case 5:
                return String.class;
            case 6:
                return Boolean.class;
            default:
                return String.class;        
          }
        }
    };
    tbl_data.setModel(model);

    // Add Column
    model.addColumn("Mã Nhân Viên");
    model.addColumn("Tên Nhân Viên");
    model.addColumn("Địa Chỉ");
    model.addColumn("Giới Tính");
    model.addColumn("Ngày Sinh");
    model.addColumn("Số Điện Thoại");
    model.addColumn("Chọn");
    String sql = "SELECT * FROM  nhanvien";
    try {
        dbConnection = MySQLConnUtils.getMySQLConnection();
        statement = dbConnection.createStatement();
        ResultSet rs = statement.executeQuery(sql);

        int row = 0;
        while ((rs != null) && (rs.next())) {
            model.addRow(new Object[0]);
            model.setValueAt(rs.getString("Ma_NV"), row, 0);
            model.setValueAt(rs.getString("Hoten"), row, 1);
            model.setValueAt(rs.getString("Diachi"), row, 2);
            
            String gioitinh;
            if (rs.getString("Gioitinh").equals("0")) {
                gioitinh = "Nữ";
            } else if (rs.getString("Gioitinh").equals("1")) {
                gioitinh = "Nam";
            } else {
               //nếu giá trị gioitinh khác 1 và 0 thì sẽ hiện lên là khác
                gioitinh = "Khác";
            }
            model.setValueAt(gioitinh, row, 3);

            
            model.setValueAt(rs.getString("Ngaysinh"), row, 4);
            model.setValueAt("0"+rs.getString("SDT"), row, 5);
            model.setValueAt(false, row, 6); // Checkbox
            
            row++;
            }
        } catch (Exception e) {
            e.printStackTrace();
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btntrangchu = new javax.swing.JPanel();
        ind1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnkhachhang = new javax.swing.JPanel();
        ind3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnnhacc = new javax.swing.JPanel();
        ind4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnloaihang = new javax.swing.JPanel();
        ind5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btndvt = new javax.swing.JPanel();
        ind6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btnkho = new javax.swing.JPanel();
        ind7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtma_nv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        r_nam = new javax.swing.JRadioButton();
        r_nu = new javax.swing.JRadioButton();
        r_khac = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        btnthem = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnsua = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        txtngay = new javax.swing.JLabel();
        txtthang = new javax.swing.JLabel();
        txtnam = new javax.swing.JLabel();
        cbngaysinh = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbexit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 34, 56));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntrangchu.setBackground(new java.awt.Color(35, 50, 75));
        btntrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btntrangchuMousePressed(evt);
            }
        });

        ind1.setBackground(new java.awt.Color(255, 255, 255));
        ind1.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind1Layout = new javax.swing.GroupLayout(ind1);
        ind1.setLayout(ind1Layout);
        ind1Layout.setHorizontalGroup(
            ind1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind1Layout.setVerticalGroup(
            ind1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Meeting_Room_32px_1.png"))); // NOI18N
        jLabel1.setText("Nhân viên");

        javax.swing.GroupLayout btntrangchuLayout = new javax.swing.GroupLayout(btntrangchu);
        btntrangchu.setLayout(btntrangchuLayout);
        btntrangchuLayout.setHorizontalGroup(
            btntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btntrangchuLayout.createSequentialGroup()
                .addComponent(ind1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        btntrangchuLayout.setVerticalGroup(
            btntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(btntrangchuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(btntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ind1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(btntrangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        btnkhachhang.setBackground(new java.awt.Color(24, 34, 56));
        btnkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnkhachhangMousePressed(evt);
            }
        });

        ind3.setBackground(new java.awt.Color(255, 255, 255));
        ind3.setOpaque(false);
        ind3.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind3Layout = new javax.swing.GroupLayout(ind3);
        ind3.setLayout(ind3Layout);
        ind3Layout.setHorizontalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind3Layout.setVerticalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Customer_32px.png"))); // NOI18N
        jLabel4.setText("Khách hàng");

        javax.swing.GroupLayout btnkhachhangLayout = new javax.swing.GroupLayout(btnkhachhang);
        btnkhachhang.setLayout(btnkhachhangLayout);
        btnkhachhangLayout.setHorizontalGroup(
            btnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnkhachhangLayout.createSequentialGroup()
                .addComponent(ind3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        btnkhachhangLayout.setVerticalGroup(
            btnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnkhachhangLayout.createSequentialGroup()
                .addGroup(btnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ind3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 260, -1));

        btnnhacc.setBackground(new java.awt.Color(24, 34, 56));
        btnnhacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnnhaccMousePressed(evt);
            }
        });

        ind4.setBackground(new java.awt.Color(255, 255, 255));
        ind4.setOpaque(false);
        ind4.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind4Layout = new javax.swing.GroupLayout(ind4);
        ind4.setLayout(ind4Layout);
        ind4Layout.setHorizontalGroup(
            ind4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind4Layout.setVerticalGroup(
            ind4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Supplier_32px_7.png"))); // NOI18N
        jLabel6.setText("Nhà cung cấp");

        javax.swing.GroupLayout btnnhaccLayout = new javax.swing.GroupLayout(btnnhacc);
        btnnhacc.setLayout(btnnhaccLayout);
        btnnhaccLayout.setHorizontalGroup(
            btnnhaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnnhaccLayout.createSequentialGroup()
                .addComponent(ind4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        btnnhaccLayout.setVerticalGroup(
            btnnhaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(btnnhaccLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ind4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnnhacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DANH MỤC");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jPanel7.setBackground(new java.awt.Color(24, 34, 56));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_32px.png"))); // NOI18N
        jLabel9.setText("Trang Chủ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 50));

        btnloaihang.setBackground(new java.awt.Color(24, 34, 56));
        btnloaihang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnloaihangMousePressed(evt);
            }
        });

        ind5.setBackground(new java.awt.Color(255, 255, 255));
        ind5.setOpaque(false);
        ind5.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind5Layout = new javax.swing.GroupLayout(ind5);
        ind5.setLayout(ind5Layout);
        ind5Layout.setHorizontalGroup(
            ind5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind5Layout.setVerticalGroup(
            ind5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Box Filled_32px.png"))); // NOI18N
        jLabel20.setText("Loại hàng");

        javax.swing.GroupLayout btnloaihangLayout = new javax.swing.GroupLayout(btnloaihang);
        btnloaihang.setLayout(btnloaihangLayout);
        btnloaihangLayout.setHorizontalGroup(
            btnloaihangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnloaihangLayout.createSequentialGroup()
                .addComponent(ind5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        btnloaihangLayout.setVerticalGroup(
            btnloaihangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnloaihangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ind5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnloaihang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, -1));

        btndvt.setBackground(new java.awt.Color(24, 34, 56));
        btndvt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btndvtMousePressed(evt);
            }
        });

        ind6.setBackground(new java.awt.Color(255, 255, 255));
        ind6.setOpaque(false);
        ind6.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind6Layout = new javax.swing.GroupLayout(ind6);
        ind6.setLayout(ind6Layout);
        ind6Layout.setHorizontalGroup(
            ind6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind6Layout.setVerticalGroup(
            ind6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Sales Performance_32px.png"))); // NOI18N
        jLabel21.setText("Đơn vị tính");

        javax.swing.GroupLayout btndvtLayout = new javax.swing.GroupLayout(btndvt);
        btndvt.setLayout(btndvtLayout);
        btndvtLayout.setHorizontalGroup(
            btndvtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndvtLayout.createSequentialGroup()
                .addComponent(ind6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        btndvtLayout.setVerticalGroup(
            btndvtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btndvtLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ind6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btndvt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 260, -1));

        btnkho.setBackground(new java.awt.Color(24, 34, 56));
        btnkho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnkhoMousePressed(evt);
            }
        });

        ind7.setBackground(new java.awt.Color(255, 255, 255));
        ind7.setOpaque(false);
        ind7.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind7Layout = new javax.swing.GroupLayout(ind7);
        ind7.setLayout(ind7Layout);
        ind7Layout.setHorizontalGroup(
            ind7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind7Layout.setVerticalGroup(
            ind7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Warehouse_32px.png"))); // NOI18N
        jLabel22.setText("Kho hàng");

        javax.swing.GroupLayout btnkhoLayout = new javax.swing.GroupLayout(btnkho);
        btnkho.setLayout(btnkhoLayout);
        btnkhoLayout.setHorizontalGroup(
            btnkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnkhoLayout.createSequentialGroup()
                .addComponent(ind7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        btnkhoLayout.setVerticalGroup(
            btnkhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnkhoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ind7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(btnkho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 650));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_data.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_data.setSelectionBackground(new java.awt.Color(60, 115, 199));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_dataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 309, 830, 300));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(60, 115, 199));
        jLabel11.setText("Mã NV ");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtma_nv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtma_nv.setForeground(new java.awt.Color(60, 115, 199));
        jPanel4.add(txtma_nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(60, 115, 199));
        jLabel12.setText("Tên NV ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(60, 115, 199));
        jLabel13.setText("Giới Tính");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(60, 115, 199));
        jLabel14.setText("Ngày Sinh");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txthoten.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txthoten.setForeground(new java.awt.Color(60, 115, 199));
        jPanel4.add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 170, 30));

        buttonGroup1.add(r_nam);
        r_nam.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        r_nam.setForeground(new java.awt.Color(0, 120, 215));
        r_nam.setText("Nam");
        jPanel4.add(r_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        buttonGroup1.add(r_nu);
        r_nu.setForeground(new java.awt.Color(0, 120, 215));
        r_nu.setText("Nữ");
        jPanel4.add(r_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        buttonGroup1.add(r_khac);
        r_khac.setForeground(new java.awt.Color(0, 120, 215));
        r_khac.setText("Khác");
        jPanel4.add(r_khac, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(60, 115, 199));
        jLabel15.setText("Địa Chỉ NV");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(60, 115, 199));
        jLabel16.setText("Số Điện Thoại");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        txtdiachi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtdiachi.setForeground(new java.awt.Color(60, 115, 199));
        jPanel4.add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 190, 30));

        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtsdt.setForeground(new java.awt.Color(60, 115, 199));
        jPanel4.add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 170, 30));

        btnthem.setBackground(new java.awt.Color(0, 120, 215));
        btnthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnthemMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Thêm Nhân Viên");

        javax.swing.GroupLayout btnthemLayout = new javax.swing.GroupLayout(btnthem);
        btnthem.setLayout(btnthemLayout);
        btnthemLayout.setHorizontalGroup(
            btnthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnthemLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(31, 31, 31))
        );
        btnthemLayout.setVerticalGroup(
            btnthemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnthemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 160, 40));

        btnxoa.setBackground(new java.awt.Color(0, 120, 215));
        btnxoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnxoaMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Xóa Nhân Viên");

        javax.swing.GroupLayout btnxoaLayout = new javax.swing.GroupLayout(btnxoa);
        btnxoa.setLayout(btnxoaLayout);
        btnxoaLayout.setHorizontalGroup(
            btnxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnxoaLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(31, 31, 31))
        );
        btnxoaLayout.setVerticalGroup(
            btnxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnxoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 160, -1));

        btnsua.setBackground(new java.awt.Color(0, 120, 215));
        btnsua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsuaMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sửa Thông Tin");

        javax.swing.GroupLayout btnsuaLayout = new javax.swing.GroupLayout(btnsua);
        btnsua.setLayout(btnsuaLayout);
        btnsuaLayout.setHorizontalGroup(
            btnsuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnsuaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btnsuaLayout.setVerticalGroup(
            btnsuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnsuaLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jPanel4.add(btnsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 160, -1));

        jPanel8.setBackground(new java.awt.Color(0, 120, 215));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NHÂN VIÊN");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Exit_32px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(174, 174, 174))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));
        jPanel4.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 60, 20));
        jPanel4.add(txtngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));
        jPanel4.add(txtthang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));
        jPanel4.add(txtnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        cbngaysinh.setBackground(new java.awt.Color(255, 255, 255));
        cbngaysinh.setForeground(new java.awt.Color(154, 0, 137));
        cbngaysinh.setDateFormatString("yyyy-MM-dd");
        cbngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel4.add(cbngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, 30));

        jPanel2.add(jPanel4, "card2");

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 850, 610));

        jPanel3.setBackground(new java.awt.Color(0, 120, 215));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 120, 215));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(67, 49, 105));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 30));

        jPanel6.setBackground(new java.awt.Color(0, 120, 215));

        lbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_32px_1.png"))); // NOI18N
        lbexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbexitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbexitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbexit))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lbexit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 850, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ngayhientai(){
        cbngaysinh.setDateFormatString("dd/MM/yyyy");
        GregorianCalendar calendar = new GregorianCalendar();
        int ngay=calendar.get(Calendar.DATE);
        int thang=calendar.get(Calendar.MONTH)+1;
        int nam=calendar.get(Calendar.YEAR);
        String ngaythang=nam+"-"+thang+"-"+ngay;
        try {
            Date date= new SimpleDateFormat("yyyy-MM-dd").parse(ngaythang);
            cbngaysinh.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(GUIDanhmuc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }   
    private void reset(){
        txtdiachi.setText("");
        txthoten.setText("");
        txtma_nv.setText("");
        txtsdt.setText("");
        buttonGroup1.clearSelection();
    }
    private void setColor(JPanel pane){
        pane.setBackground(new Color(35, 50, 75));
    }
    
    private void resetColor(JPanel [] pane,JPanel[] indicators){
        for(int i=0;i<pane.length;i++)
            pane[i].setBackground(new Color(24,34,56));
        for(int i=0;i<indicators.length;i++)
            indicators[i].setOpaque(false);
    }
    Danhmuc_nhacc caidat=new Danhmuc_nhacc();
    Danhmuc_khachhang nguoidung=new Danhmuc_khachhang();
    Danhmuc_loaihang loaihang = new Danhmuc_loaihang();
    Danhmuc_donvitinh dvt = new Danhmuc_donvitinh();
    Danhmuc_khohang kho = new Danhmuc_khohang();
    private void btntrangchuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrangchuMousePressed
        setColor(btntrangchu);//doi mau
        ind1.setOpaque(true);
        resetColor(new JPanel[]{btnnhacc,btnkhachhang,btnloaihang,btndvt,btnkho},new JPanel[]{ind3,ind4,ind5,ind6,ind7});
        //doi trang
        jPanel4.setVisible(true);
   

        jPanel2.add(caidat, "card2");
        caidat.setVisible(false);
        jPanel2.add(nguoidung, "card2");
        nguoidung.setVisible(false);
        jPanel2.add(loaihang, "card2");
        loaihang.setVisible(false);
        jPanel2.add(dvt, "card2");
        dvt.setVisible(false);  
        jPanel2.add(kho, "card2");
        kho.setVisible(false); 
    }//GEN-LAST:event_btntrangchuMousePressed

    private void btnnhaccMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnhaccMousePressed
        setColor(btnnhacc);
        ind4.setOpaque(true);
        resetColor(new JPanel[]{btntrangchu,btnkhachhang,btnloaihang,btndvt,btnkho},new JPanel[]{ind3,ind1,ind5,ind6,ind7});
        //
        jPanel4.setVisible(false);
        

        jPanel2.add(caidat, "card2");
        caidat.setVisible(true);
        jPanel2.add(nguoidung, "card2");
        nguoidung.setVisible(false);
        jPanel2.add(loaihang, "card2");
        loaihang.setVisible(false);
        jPanel2.add(dvt, "card2");
        dvt.setVisible(false);   
        jPanel2.add(kho, "card2");
        kho.setVisible(false);
    }//GEN-LAST:event_btnnhaccMousePressed

    private void btnkhachhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhachhangMousePressed
        setColor(btnkhachhang);
        ind3.setOpaque(true);
        resetColor(new JPanel[]{btnnhacc,btntrangchu,btnloaihang,btndvt,btnkho},new JPanel[]{ind1,ind4,ind5,ind6,ind7});
        
        jPanel4.setVisible(false);
        

        jPanel2.add(caidat, "card2");
        caidat.setVisible(false);
        jPanel2.add(nguoidung, "card2");
        nguoidung.setVisible(true);
        jPanel2.add(loaihang, "card2");
        loaihang.setVisible(false);
        jPanel2.add(dvt, "card2");
        dvt.setVisible(false);      
        jPanel2.add(kho, "card2");
        kho.setVisible(false);
    }//GEN-LAST:event_btnkhachhangMousePressed

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(new Color(0,120,215));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void lbexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexitMouseEntered
        lbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_32px_3.png")));
        jPanel6.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbexitMouseEntered

    private void lbexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexitMouseExited
        lbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_32px_1.png")));
        jPanel6.setBackground(new Color(0,120,215));
    }//GEN-LAST:event_lbexitMouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        jPanel7.setBackground(new Color(35, 50, 75));
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setBackground(new Color (24, 34, 56));
    }//GEN-LAST:event_jPanel7MouseExited

    private void btnthemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemMouseClicked
        boolean isNumeric = true;
        
        try {
            int num = Integer.parseInt(txtsdt.getText());
            isNumeric = true;

         } catch (NumberFormatException e) {
            isNumeric = false;
        }
        if (isNumeric) {
            Danhmuc danhmuc = new Danhmuc();
            danhmuc.setMa_NV(txtma_nv.getText());
            danhmuc.setHoten(txthoten.getText());

            if (buttonGroup1.getSelection() != null) {
                if (buttonGroup1.getSelection().getActionCommand().equals("Nữ")) {
                    danhmuc.setGioitinh(0);
                } else if (buttonGroup1.getSelection().getActionCommand().equals("Nam")) {
                    danhmuc.setGioitinh(1);
                } else {
                    danhmuc.setGioitinh(2);
                }
            } else {
                //Nếu người dùng không chọn ô button nào thì gioitinh sẽ để mặc định là 2
                 danhmuc.setGioitinh(2);
            }    
            danhmuc.setDiachi(txtdiachi.getText());

            Date date = cbngaysinh.getDate();
            String dateInput = new SimpleDateFormat("yyyy-MM-dd").format(date);
            danhmuc.setNgaysinh(dateInput);

            danhmuc.setSDT(Integer.parseInt(txtsdt.getText()));

            if(DAOdanhmuc.ThemNhanvien(danhmuc)){
                if (txtma_nv.getText().equals("") || txthoten.getText().equals("")) {
                    //nếu 1 số ô trong đó để rỗng sẽ đưa ra thông báo
                    JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }else {
                    //ngược lại thực hiện lấy dữ liệu trong các ô để đưa vào CSDL
                     DAOdanhmuc.ThemNhanvien(danhmuc);

                    JOptionPane.showMessageDialog(this, "Thêm mới Nhân viên thành công!");//đưa ra thông báo khi thực hiện thành công
                    loadData();//load lại form
                    reset();//xóa dữ liệu trong các ô text
                    txtma_nv.setEditable(true);
                }
            }else{
            JOptionPane.showMessageDialog(this, "Mã số nhân viên đã bị trùng!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            loadData();
            reset();
        }
 
        }
            else {
                JOptionPane.showMessageDialog(this, "SDT của nhân viên phải nhập số!", "Thông báo", JOptionPane.WARNING_MESSAGE); 
            }
    }//GEN-LAST:event_btnthemMouseClicked

    private void btnxoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxoaMouseClicked
        Integer confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa người dùng này không?", "Xóa", 2);
        //khi người dùng ấn đồng ý
        if (confirm == JOptionPane.YES_OPTION) {

            for (int i = 0; i < tbl_data.getRowCount(); i++) {
                Boolean chkDel = Boolean.valueOf(tbl_data.getValueAt(i, 6).toString()); // Checked
                if(chkDel){
                    String danhmuc = tbl_data.getValueAt(i, 0).toString();

                    DAOdanhmuc.XoaNhanVien(danhmuc); // Delete Data
                    reset();
                    
                }
            }
            JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công!");
            loadData(); // Reload Table
        }else{
            reset();
        }
   
    }//GEN-LAST:event_btnxoaMouseClicked

    private void btnsuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsuaMouseClicked
        Danhmuc danhmuc = new Danhmuc();
        danhmuc.setMa_NV(txtma_nv.getText());
        danhmuc.setHoten(txthoten.getText());
        danhmuc.setDiachi(txtdiachi.getText());

        if (buttonGroup1.getSelection().getActionCommand().equals("Nữ")) {
            danhmuc.setGioitinh(0);
        } else if (buttonGroup1.getSelection().getActionCommand().equals("Nam")) {
            danhmuc.setGioitinh(1);
        } else {
            danhmuc.setGioitinh(2);
        }

        Date date = cbngaysinh.getDate();
        String dateInput = new SimpleDateFormat("yyyy-MM-dd").format(date);
        
        danhmuc.setNgaysinh(dateInput);

        danhmuc.setSDT(Integer.parseInt(txtsdt.getText()));
        DAOdanhmuc.SuaNhanVien(danhmuc);
        txtma_nv.setEditable(true);
        JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!");//đưa ra thông báo khi thực hiện thành công
        loadData();//load lại form
        reset();
    }//GEN-LAST:event_btnsuaMouseClicked

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        new Main.Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel7MousePressed

    private void lbexitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexitMousePressed
        int i = JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn thoát!","Thoát",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
	if (i==0){
            System.exit(0);
	}
    }//GEN-LAST:event_lbexitMousePressed

    private void tbl_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMousePressed
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        int row = tbl_data.getSelectedRow();
        String ma_nv = tbl_data.getValueAt(row, 0).toString();
        Danhmuc danhmuc = new Danhmuc();
        danhmuc = DAOdanhmuc.TimNhanvien(ma_nv);
        txtma_nv.setText(ma_nv);
        txthoten.setText(danhmuc.getHoten());
        txtdiachi.setText(danhmuc.getDiachi());
        if (danhmuc.getGioitinh() == 0) {
            r_nu.setSelected(true);
        } else if (danhmuc.getGioitinh() == 1) {
            r_nam.setSelected(true);
        } else {
            r_khac.setSelected(true);
        }
        txtsdt.setText(danhmuc.getSDT().toString());
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(row, 4));
            cbngaysinh.setDate(date);
        } catch (Exception ex) {
           
        }
        txtma_nv.setEditable(false);
    }//GEN-LAST:event_tbl_dataMousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int i = JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn đăng xuất!","Đăng Xuất",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
	if (i==0){
            new Login().setVisible(true);
            this.dispose();
	}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnloaihangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloaihangMousePressed
        setColor(btnloaihang);
        ind5.setOpaque(true);
        resetColor(new JPanel[]{btnnhacc,btntrangchu,btnkhachhang,btndvt,btnkho},new JPanel[]{ind1,ind4,ind3,ind6,ind7});
        
        jPanel4.setVisible(false);
        
        jPanel2.add(caidat, "card2");
        caidat.setVisible(false);
        jPanel2.add(nguoidung, "card2");
        nguoidung.setVisible(false);
        jPanel2.add(loaihang, "card2");
        loaihang.setVisible(true);
        jPanel2.add(dvt, "card2");
        dvt.setVisible(false);    
        jPanel2.add(kho, "card2");
        kho.setVisible(false);
    }//GEN-LAST:event_btnloaihangMousePressed

    private void btndvtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndvtMousePressed
        setColor(btndvt);
        ind6.setOpaque(true);
        resetColor(new JPanel[]{btnnhacc,btntrangchu,btnloaihang,btnkhachhang,btnkho},new JPanel[]{ind1,ind4,ind5,ind3,ind7});
        
        jPanel4.setVisible(false);
        

        jPanel2.add(caidat, "card2");
        caidat.setVisible(false);
        jPanel2.add(nguoidung, "card2");
        nguoidung.setVisible(false);
        jPanel2.add(loaihang, "card2");
        loaihang.setVisible(false);
        jPanel2.add(dvt, "card2");
        dvt.setVisible(true);    
        jPanel2.add(kho, "card2");
        kho.setVisible(false);
    }//GEN-LAST:event_btndvtMousePressed

    private void btnkhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkhoMousePressed
        setColor(btnkho);
        ind7.setOpaque(true);
        resetColor(new JPanel[]{btnnhacc,btntrangchu,btnloaihang,btndvt,btnkhachhang},new JPanel[]{ind1,ind4,ind5,ind6,ind3});
        
        jPanel4.setVisible(false);
        

        jPanel2.add(caidat, "card2");
        caidat.setVisible(false);
        jPanel2.add(nguoidung, "card2");
        nguoidung.setVisible(false);
        jPanel2.add(loaihang, "card2");
        loaihang.setVisible(false);
        jPanel2.add(dvt, "card2");
        dvt.setVisible(false);   
        jPanel2.add(kho, "card2");
        kho.setVisible(true);
    }//GEN-LAST:event_btnkhoMousePressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {//Nimbus
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDanhmuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JPanel btndvt;
    private javax.swing.JPanel btnkhachhang;
    private javax.swing.JPanel btnkho;
    private javax.swing.JPanel btnloaihang;
    private javax.swing.JPanel btnnhacc;
    private javax.swing.JPanel btnsua;
    private javax.swing.JPanel btnthem;
    private javax.swing.JPanel btntrangchu;
    private javax.swing.JPanel btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser cbngaysinh;
    private javax.swing.JPanel ind1;
    private javax.swing.JPanel ind3;
    private javax.swing.JPanel ind4;
    private javax.swing.JPanel ind5;
    private javax.swing.JPanel ind6;
    private javax.swing.JPanel ind7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbexit;
    private javax.swing.JRadioButton r_khac;
    private javax.swing.JRadioButton r_nam;
    private javax.swing.JRadioButton r_nu;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtma_nv;
    private javax.swing.JLabel txtnam;
    private javax.swing.JLabel txtngay;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JLabel txtthang;
    // End of variables declaration//GEN-END:variables
}
