
package GUI;

import DAOGUI.DAONghiepvu;
import DBConnect.MySQLConnUtils;
import Frame.*;
import OBJFrame.Dm_khohang;
import OBJGUI.Nghiepvu;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class GUINghiepvu extends javax.swing.JFrame {
    DAOGUI.DAONghiepvu DAOnghiepvu = new DAONghiepvu();

    public GUINghiepvu() {
        initComponents();
        setLocationRelativeTo(null);
        loadData();
        cb_mahang();
        cb_makh();
        cb_manv();
        table();
        ngayhientai();
    }

    Connection dbConnection = null;
    Statement statement = null;
    public void loadData() {
        // Clear table
        tbl_data.setModel(new DefaultTableModel());
        // Model for Table
        DefaultTableModel model = new DefaultTableModel() {
            public Class<?> getColumnClass(int column) {
                switch (column) {
                case 0:
                    return String.class;
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return String.class;
                case 5:
                    return String.class;   

                default:
                    return String.class;        
              }
            }
        };
        tbl_data.setModel(model);

        // Add Column
        model.addColumn("Mã hàng");
        model.addColumn("Tên hàng");
        model.addColumn("Đơn giá");
        model.addColumn("Số lượng");
        model.addColumn("Giảm giá");
        model.addColumn("Thành tiền");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnbanhang = new javax.swing.JPanel();
        ind2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btntrahang = new javax.swing.JPanel();
        ind3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnnhaphang = new javax.swing.JPanel();
        ind4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnhoadonban = new javax.swing.JPanel();
        ind5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnhoadontra = new javax.swing.JPanel();
        ind7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnhoadonnhap = new javax.swing.JPanel();
        ind8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbexit = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_tongtien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_tenkh = new javax.swing.JTextField();
        txt_giamgia = new javax.swing.JTextField();
        cb_mahang = new javax.swing.JComboBox();
        cb_makh = new javax.swing.JComboBox();
        txt_tennv = new javax.swing.JTextField();
        cb_manv = new javax.swing.JComboBox();
        txt_tenhang = new javax.swing.JTextField();
        txt_dongia = new javax.swing.JTextField();
        txt_sluong = new javax.swing.JTextField();
        txt_tonkho = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_datra = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        cbngayxuat = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 0, 45));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Home_32px.png"))); // NOI18N
        jLabel1.setText("Trang Chủ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, -1));

        btnbanhang.setBackground(new java.awt.Color(119, 85, 115));
        btnbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbanhangMousePressed(evt);
            }
        });

        ind2.setBackground(new java.awt.Color(255, 255, 255));
        ind2.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind2Layout = new javax.swing.GroupLayout(ind2);
        ind2.setLayout(ind2Layout);
        ind2Layout.setHorizontalGroup(
            ind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind2Layout.setVerticalGroup(
            ind2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Sell_32px_1.png"))); // NOI18N
        jLabel3.setText("Bán hàng");

        javax.swing.GroupLayout btnbanhangLayout = new javax.swing.GroupLayout(btnbanhang);
        btnbanhang.setLayout(btnbanhangLayout);
        btnbanhangLayout.setHorizontalGroup(
            btnbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnbanhangLayout.createSequentialGroup()
                .addComponent(ind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        btnbanhangLayout.setVerticalGroup(
            btnbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnbanhangLayout.createSequentialGroup()
                .addGroup(btnbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnbanhangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        jPanel1.add(btnbanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, 50));

        btntrahang.setBackground(new java.awt.Color(51, 0, 45));
        btntrahang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btntrahangMousePressed(evt);
            }
        });

        ind3.setBackground(new java.awt.Color(255, 255, 255));
        ind3.setOpaque(false);
        ind3.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind3Layout = new javax.swing.GroupLayout(ind3);
        ind3.setLayout(ind3Layout);
        ind3Layout.setHorizontalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind3Layout.setVerticalGroup(
            ind3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Checkout_32px.png"))); // NOI18N
        jLabel4.setText("Trả hàng nhà cung cấp");

        javax.swing.GroupLayout btntrahangLayout = new javax.swing.GroupLayout(btntrahang);
        btntrahang.setLayout(btntrahangLayout);
        btntrahangLayout.setHorizontalGroup(
            btntrahangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btntrahangLayout.createSequentialGroup()
                .addComponent(ind3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        btntrahangLayout.setVerticalGroup(
            btntrahangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addGroup(btntrahangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btntrahang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, 50));

        btnnhaphang.setBackground(new java.awt.Color(51, 0, 45));
        btnnhaphang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnnhaphangMousePressed(evt);
            }
        });

        ind4.setBackground(new java.awt.Color(255, 255, 255));
        ind4.setOpaque(false);
        ind4.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind4Layout = new javax.swing.GroupLayout(ind4);
        ind4.setLayout(ind4Layout);
        ind4Layout.setHorizontalGroup(
            ind4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind4Layout.setVerticalGroup(
            ind4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Buy_32px.png"))); // NOI18N
        jLabel5.setText("Nhập hàng");

        javax.swing.GroupLayout btnnhaphangLayout = new javax.swing.GroupLayout(btnnhaphang);
        btnnhaphang.setLayout(btnnhaphangLayout);
        btnnhaphangLayout.setHorizontalGroup(
            btnnhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnnhaphangLayout.createSequentialGroup()
                .addComponent(ind4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        btnnhaphangLayout.setVerticalGroup(
            btnnhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addGroup(btnnhaphangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnnhaphang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 300, 50));

        btnhoadonban.setBackground(new java.awt.Color(51, 0, 45));
        btnhoadonban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnhoadonbanMousePressed(evt);
            }
        });

        ind5.setBackground(new java.awt.Color(255, 255, 255));
        ind5.setOpaque(false);
        ind5.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind5Layout = new javax.swing.GroupLayout(ind5);
        ind5.setLayout(ind5Layout);
        ind5Layout.setHorizontalGroup(
            ind5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind5Layout.setVerticalGroup(
            ind5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Bill_32px.png"))); // NOI18N
        jLabel6.setText("Hóa đơn bán hàng");

        javax.swing.GroupLayout btnhoadonbanLayout = new javax.swing.GroupLayout(btnhoadonban);
        btnhoadonban.setLayout(btnhoadonbanLayout);
        btnhoadonbanLayout.setHorizontalGroup(
            btnhoadonbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnhoadonbanLayout.createSequentialGroup()
                .addComponent(ind5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        btnhoadonbanLayout.setVerticalGroup(
            btnhoadonbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addGroup(btnhoadonbanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnhoadonban, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 300, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NGHIỆP VỤ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnhoadontra.setBackground(new java.awt.Color(51, 0, 45));
        btnhoadontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnhoadontraMousePressed(evt);
            }
        });

        ind7.setBackground(new java.awt.Color(255, 255, 255));
        ind7.setOpaque(false);
        ind7.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind7Layout = new javax.swing.GroupLayout(ind7);
        ind7.setLayout(ind7Layout);
        ind7Layout.setHorizontalGroup(
            ind7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind7Layout.setVerticalGroup(
            ind7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Bill_32px.png"))); // NOI18N
        jLabel11.setText("Hóa đơn trả nhà cung cấp");

        javax.swing.GroupLayout btnhoadontraLayout = new javax.swing.GroupLayout(btnhoadontra);
        btnhoadontra.setLayout(btnhoadontraLayout);
        btnhoadontraLayout.setHorizontalGroup(
            btnhoadontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnhoadontraLayout.createSequentialGroup()
                .addComponent(ind7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        btnhoadontraLayout.setVerticalGroup(
            btnhoadontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addGroup(btnhoadontraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnhoadontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 300, 50));

        btnhoadonnhap.setBackground(new java.awt.Color(51, 0, 45));
        btnhoadonnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnhoadonnhapMousePressed(evt);
            }
        });

        ind8.setBackground(new java.awt.Color(255, 255, 255));
        ind8.setOpaque(false);
        ind8.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind8Layout = new javax.swing.GroupLayout(ind8);
        ind8.setLayout(ind8Layout);
        ind8Layout.setHorizontalGroup(
            ind8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind8Layout.setVerticalGroup(
            ind8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Bill_32px.png"))); // NOI18N
        jLabel12.setText("Hóa đơn nhập hàng");

        javax.swing.GroupLayout btnhoadonnhapLayout = new javax.swing.GroupLayout(btnhoadonnhap);
        btnhoadonnhap.setLayout(btnhoadonnhapLayout);
        btnhoadonnhapLayout.setHorizontalGroup(
            btnhoadonnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnhoadonnhapLayout.createSequentialGroup()
                .addComponent(ind8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        btnhoadonnhapLayout.setVerticalGroup(
            btnhoadonnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind8, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addGroup(btnhoadonnhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(btnhoadonnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 300, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 650));

        jPanel2.setBackground(new java.awt.Color(154, 0, 137));

        jPanel7.setBackground(new java.awt.Color(154, 0, 137));

        lbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_32px_1.png"))); // NOI18N
        lbexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbexitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbexitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbexit))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lbexit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(154, 0, 137));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 810, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 870, 40));

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(154, 0, 137));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BÁN HÀNG");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 80));

        lb_tongtien.setBackground(new java.awt.Color(154, 0, 137));
        lb_tongtien.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lb_tongtien.setForeground(new java.awt.Color(154, 0, 137));
        jPanel5.add(lb_tongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 140, 20));

        tbl_data.setForeground(new java.awt.Color(154, 0, 137));
        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_data.setSelectionBackground(new java.awt.Color(154, 0, 137));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_dataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 850, 260));

        jLabel14.setBackground(new java.awt.Color(154, 0, 137));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(154, 0, 137));
        jLabel14.setText("Thông tin các mặt hàng");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel15.setBackground(new java.awt.Color(154, 0, 137));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(154, 0, 137));
        jLabel15.setText("Thông tin chung");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel16.setBackground(new java.awt.Color(154, 0, 137));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(154, 0, 137));
        jLabel16.setText("Đã trả");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        jLabel17.setBackground(new java.awt.Color(154, 0, 137));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(154, 0, 137));
        jLabel17.setText("Ngày bán");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jLabel18.setBackground(new java.awt.Color(154, 0, 137));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(154, 0, 137));
        jLabel18.setText("Mã nhân viên");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel19.setBackground(new java.awt.Color(154, 0, 137));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(154, 0, 137));
        jLabel19.setText("Tên nhân viên");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel20.setBackground(new java.awt.Color(154, 0, 137));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(154, 0, 137));
        jLabel20.setText("Mã khách hàng");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel21.setBackground(new java.awt.Color(154, 0, 137));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(154, 0, 137));
        jLabel21.setText("Tên khách hàng");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jPanel10.setBackground(new java.awt.Color(154, 0, 137));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Thêm hàng");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 130, -1));

        jPanel11.setBackground(new java.awt.Color(154, 0, 137));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Lập hóa đơn");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel24)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 130, -1));

        jLabel26.setBackground(new java.awt.Color(154, 0, 137));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(154, 0, 137));
        jLabel26.setText("Mã hàng");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel27.setBackground(new java.awt.Color(154, 0, 137));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(154, 0, 137));
        jLabel27.setText("Tên hàng");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel28.setBackground(new java.awt.Color(154, 0, 137));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(154, 0, 137));
        jLabel28.setText("Số lượng");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jLabel29.setBackground(new java.awt.Color(154, 0, 137));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(154, 0, 137));
        jLabel29.setText("Tồn kho");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabel30.setBackground(new java.awt.Color(154, 0, 137));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(154, 0, 137));
        jLabel30.setText("Đơn giá");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        txt_tenkh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tenkh.setForeground(new java.awt.Color(154, 0, 137));
        jPanel5.add(txt_tenkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 120, 30));

        txt_giamgia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_giamgia.setForeground(new java.awt.Color(154, 0, 137));
        txt_giamgia.setText("0");
        jPanel5.add(txt_giamgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 90, 30));

        cb_mahang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_mahang.setForeground(new java.awt.Color(154, 0, 137));
        cb_mahang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mahangActionPerformed(evt);
            }
        });
        jPanel5.add(cb_mahang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 110, 30));

        cb_makh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_makh.setForeground(new java.awt.Color(154, 0, 137));
        cb_makh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_makhActionPerformed(evt);
            }
        });
        jPanel5.add(cb_makh, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 120, 30));

        txt_tennv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tennv.setForeground(new java.awt.Color(154, 0, 137));
        jPanel5.add(txt_tennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, 30));

        cb_manv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_manv.setForeground(new java.awt.Color(154, 0, 137));
        cb_manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_manvActionPerformed(evt);
            }
        });
        jPanel5.add(cb_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, 30));

        txt_tenhang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tenhang.setForeground(new java.awt.Color(154, 0, 137));
        jPanel5.add(txt_tenhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 220, 30));

        txt_dongia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_dongia.setForeground(new java.awt.Color(154, 0, 137));
        jPanel5.add(txt_dongia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 130, 30));

        txt_sluong.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_sluong.setForeground(new java.awt.Color(154, 0, 137));
        jPanel5.add(txt_sluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 100, 30));

        txt_tonkho.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tonkho.setForeground(new java.awt.Color(154, 0, 137));
        jPanel5.add(txt_tonkho, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 100, 30));

        jPanel12.setBackground(new java.awt.Color(154, 0, 137));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Xóa hàng");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel32)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        jLabel22.setBackground(new java.awt.Color(154, 0, 137));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(154, 0, 137));
        jLabel22.setText("Tổng tiền:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, -1));

        jLabel33.setBackground(new java.awt.Color(154, 0, 137));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(154, 0, 137));
        jLabel33.setText("Giảm giá");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        txt_datra.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_datra.setForeground(new java.awt.Color(154, 0, 137));
        txt_datra.setText("0");
        jPanel5.add(txt_datra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 110, 30));

        jPanel13.setBackground(new java.awt.Color(154, 0, 137));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("In hóa đơn");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel34)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 130, -1));

        cbngayxuat.setBackground(new java.awt.Color(255, 255, 255));
        cbngayxuat.setForeground(new java.awt.Color(154, 0, 137));
        cbngayxuat.setDateFormatString("yyyy-MM-dd");
        cbngayxuat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel5.add(cbngayxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Synchronize_20px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, 30));

        jPanel4.add(jPanel5, "card2");

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 870, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void table(){
        for(int i=0;i<6;i++){
            TableColumn column = null;
            column=tbl_data.getColumnModel().getColumn(i);
            if(i==0)
                column.setPreferredWidth(100);
            if(i==1)
                column.setPreferredWidth(300);
        }
    }
    private void reset(){
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        model.setRowCount(0);
        ngayhientai();
        cb_manv.setSelectedIndex(0);
        cb_makh.setSelectedIndex(0);
        default_mahang();
        default_makh();
        default_manv();
        txt_giamgia.setText("0");
        txt_datra.setText("0");
        txt_sluong.setText("");
        lb_tongtien.setText("");
    }
    private void ngayhientai(){
        cbngayxuat.setDateFormatString("dd/MM/yyyy");
        GregorianCalendar calendar = new GregorianCalendar();
        int ngay=calendar.get(Calendar.DATE);
        int thang=calendar.get(Calendar.MONTH)+1;
        int nam=calendar.get(Calendar.YEAR);
        String ngaythang=nam+"-"+thang+"-"+ngay;
        try {
            Date date= new SimpleDateFormat("yyyy-MM-dd").parse(ngaythang);
            cbngayxuat.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(GUINghiepvu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void setColor(JPanel pane){
        pane.setBackground(new Color(119,85,115));
    }
    private void resetColor(JPanel [] pane,JPanel[] indicators){
        for(int i=0;i<pane.length;i++)
            pane[i].setBackground(new Color(51,0,45));
        for(int i=0;i<indicators.length;i++)
            indicators[i].setOpaque(false);
    }

    Nghiepvu_hoadonbanhang hdbanhang=new Nghiepvu_hoadonbanhang();
    Nghiepvu_hoadonnhaphang hdnhaphang=new Nghiepvu_hoadonnhaphang();
    Nghiepvu_hoadontrahang hdtrahang=new Nghiepvu_hoadontrahang();
    Nghiepvu_nhaphang nhaphang=new Nghiepvu_nhaphang();
    Nghiepvu_trahang trahang=new Nghiepvu_trahang();
    
    private void btnbanhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbanhangMousePressed
        setColor(btnbanhang);//doi mau
        ind2.setOpaque(true);
        resetColor(new JPanel[]{btnhoadonban,btnnhaphang,btntrahang,btnhoadontra,btnhoadonnhap},
                new JPanel[]{ind3,ind4,ind5,ind7,ind8});
        //doi trang
        jPanel5.setVisible(true);


        jPanel4.add(hdbanhang, "card2");
        hdbanhang.setVisible(false);
        jPanel4.add(nhaphang, "card2");
        nhaphang.setVisible(false);
        jPanel4.add(trahang, "card2");
        trahang.setVisible(false);
        jPanel4.add(hdnhaphang, "card2");
        hdnhaphang.setVisible(false);
        jPanel4.add(hdtrahang, "card2");
        hdtrahang.setVisible(false);  

    }//GEN-LAST:event_btnbanhangMousePressed

    private void btntrahangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrahangMousePressed
        setColor(btntrahang);//doi mau
        ind3.setOpaque(true);
        resetColor(new JPanel[]{btnhoadonban,btnnhaphang,btnbanhang,btnhoadontra,btnhoadonnhap},
                new JPanel[]{ind2,ind4,ind5,ind7,ind8});
        //doi trang
        jPanel5.setVisible(false);


        jPanel4.add(hdbanhang, "card2");
        hdbanhang.setVisible(false);
        jPanel4.add(nhaphang, "card2");
        nhaphang.setVisible(false);
        jPanel4.add(trahang, "card2");
        trahang.setVisible(true);
        jPanel4.add(hdnhaphang, "card2");
        hdnhaphang.setVisible(false);
        jPanel4.add(hdtrahang, "card2");
        hdtrahang.setVisible(false); 
    }//GEN-LAST:event_btntrahangMousePressed

    private void btnnhaphangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnhaphangMousePressed
        setColor(btnnhaphang);//doi mau
        ind4.setOpaque(true);
        resetColor(new JPanel[]{btnbanhang,btnhoadonban,btntrahang,btnhoadontra,btnhoadonnhap},
                new JPanel[]{ind2,ind3,ind5,ind7,ind8});
        //doi trang
        jPanel5.setVisible(false);


        jPanel4.add(hdbanhang, "card2");
        hdbanhang.setVisible(false);
        jPanel4.add(nhaphang, "card2");
        nhaphang.setVisible(true);
        jPanel4.add(trahang, "card2");
        trahang.setVisible(false);
        jPanel4.add(hdnhaphang, "card2");
        hdnhaphang.setVisible(false);
        jPanel4.add(hdtrahang, "card2");
        hdtrahang.setVisible(false); 
    }//GEN-LAST:event_btnnhaphangMousePressed

    private void btnhoadonbanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhoadonbanMousePressed
        setColor(btnhoadonban);//doi mau
        ind5.setOpaque(true);
        resetColor(new JPanel[]{btnbanhang,btnnhaphang,btntrahang,btnhoadontra,btnhoadonnhap},
                new JPanel[]{ind2,ind3,ind4,ind7,ind8});
        //doi trang
        jPanel5.setVisible(false);


        jPanel4.add(hdbanhang, "card2");
        hdbanhang.setVisible(true);
        jPanel4.add(nhaphang, "card2");
        nhaphang.setVisible(false);
        jPanel4.add(trahang, "card2");
        trahang.setVisible(false);
        jPanel4.add(hdnhaphang, "card2");
        hdnhaphang.setVisible(false);
        jPanel4.add(hdtrahang, "card2");
        hdtrahang.setVisible(false); 
    }//GEN-LAST:event_btnhoadonbanMousePressed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(new Color(119,85,115));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(new Color(51,0,45));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        new Main.Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MousePressed

    private void lbexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexitMouseEntered
        lbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_32px_3.png")));
        jPanel7.setBackground(Color.WHITE);
    }//GEN-LAST:event_lbexitMouseEntered

    private void lbexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexitMouseExited
        lbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_32px_1.png")));
        jPanel7.setBackground(new Color(154,0,137));
    }//GEN-LAST:event_lbexitMouseExited

    private void lbexitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbexitMousePressed
        int i = JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn Thoát!","Thông Báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (i==0){
            this.dispose();
        }
    }//GEN-LAST:event_lbexitMousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jPanel8.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jPanel8.setBackground(new Color (154,0,137));
    }//GEN-LAST:event_jLabel9MouseExited

    private void btnhoadontraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhoadontraMousePressed
        setColor(btnhoadontra);//doi mau
        ind7.setOpaque(true);
        resetColor(new JPanel[]{btnbanhang,btnnhaphang,btntrahang,btnhoadonban,btnhoadonnhap},
                new JPanel[]{ind2,ind3,ind4,ind5,ind8});
        //doi trang
        jPanel5.setVisible(false);

        jPanel4.add(hdbanhang, "card2");
        hdbanhang.setVisible(false);
        jPanel4.add(nhaphang, "card2");
        nhaphang.setVisible(false);
        jPanel4.add(trahang, "card2");
        trahang.setVisible(false);
        jPanel4.add(hdnhaphang, "card2");
        hdnhaphang.setVisible(false);
        jPanel4.add(hdtrahang, "card2");
        hdtrahang.setVisible(true);
    }//GEN-LAST:event_btnhoadontraMousePressed

    private void btnhoadonnhapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhoadonnhapMousePressed
        setColor(btnhoadonnhap);//doi mau
        ind8.setOpaque(true);
        resetColor(new JPanel[]{btnbanhang,btnnhaphang,btntrahang,btnhoadonban,btnhoadontra},
                new JPanel[]{ind2,ind3,ind4,ind5,ind7});
        //doi trang
        jPanel5.setVisible(false);

        jPanel4.add(hdbanhang, "card2");
        hdbanhang.setVisible(false);
        jPanel4.add(nhaphang, "card2");
        nhaphang.setVisible(false);
        jPanel4.add(trahang, "card2");
        trahang.setVisible(false);
        jPanel4.add(hdnhaphang, "card2");
        hdnhaphang.setVisible(true);
        jPanel4.add(hdtrahang, "card2");
        hdtrahang.setVisible(false);
    }//GEN-LAST:event_btnhoadonnhapMousePressed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        int soluongmua=0;
        if(Integer.parseInt(txt_sluong.getText())>Integer.parseInt(txt_tonkho.getText())){
            JOptionPane.showMessageDialog(this, "Bạn không thể mua quá số lượng tồn kho!" , "Thông báo", JOptionPane.WARNING_MESSAGE);
                txt_sluong.setText("");
        }else{
//            for(int i=0;i<tbl_data.getRowCount();i++){
//            if(Integer.parseInt(cb_mahang.getSelectedItem().toString())==Integer.parseInt(tbl_data.getValueAt(i, 0).toString())){
//                soluongmua=soluongmua+Integer.parseInt(tbl_data.getValueAt(i, 3).toString())+Integer.parseInt(txt_sluong.getText());
//            }
            
//            }
            if (txt_sluong.getText().equals("") || txt_tenhang.getText().equals("")|| txt_tonkho.getText().equals("")
                    || txt_giamgia.getText().equals("")) {
                    //nếu 1 số ô trong đó để rỗng sẽ đưa ra thông báo
                    JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }else {

                if(soluongmua>Integer.parseInt(txt_tonkho.getText())){
                    JOptionPane.showMessageDialog(this, "Bạn không thể mua quá số lượng tồn kho!" , "Thông báo", JOptionPane.WARNING_MESSAGE);
                    txt_sluong.setText("");
                }
                else{
                    int gia=Integer.parseInt(txt_dongia.getText())*Integer.parseInt(txt_sluong.getText());
                    int thanhtien=gia-Integer.parseInt(txt_giamgia.getText())*gia/100;
                    model.addRow(new Object[]{cb_mahang.getSelectedItem().toString(),txt_tenhang.getText(), txt_dongia.getText(),
                    txt_sluong.getText(),txt_giamgia.getText(),thanhtien});
                    txt_dongia.setText("");
                    txt_tenhang.setText("");
                    txt_tonkho.setText("");
                    txt_datra.setText("0");
                    txt_sluong.setText("");
                    txt_giamgia.setText("0");
                    cb_mahang.setSelectedIndex(0);
                    default_mahang();
                    int tongtien=0;
                    for(int j = 0;j<tbl_data.getRowCount();j++){
                        tongtien=tongtien+Integer.parseInt(tbl_data.getValueAt(j, 5).toString());
                    }

                    Locale localeVN = new Locale("vi", "VN");
                    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
                    String tien = currencyVN.format(tongtien);
                    lb_tongtien.setText(tien);

                }
            }
        }
        
    }//GEN-LAST:event_jPanel10MouseClicked
    private void hoadonX(){
        Nghiepvu xuathang = new Nghiepvu();
        Date date = cbngayxuat.getDate();
        String dateInput = new SimpleDateFormat("yyyy-MM-dd").format(date);
        boolean isNumeric = true;
        
        try {

            int num2=Integer.parseInt(txt_datra.getText());

            isNumeric = true;

         } catch (NumberFormatException e) {
            isNumeric = false;
        }
        int tongtien=0;
            for(int i = 0;i<tbl_data.getRowCount();i++){
                tongtien=tongtien+Integer.parseInt(tbl_data.getValueAt(i, 5).toString());
            }
        if (isNumeric) {     
            xuathang.setNgay_xuat(dateInput);
            xuathang.setThanhtienxuat(tongtien);
            xuathang.setDa_tra(Integer.parseInt(txt_datra.getText()));
            xuathang.setMa_NV(cb_manv.getSelectedItem().toString());
            xuathang.setMa_KH(cb_makh.getSelectedItem().toString());
            
            DAOnghiepvu.ThemHoadonX(xuathang); 

            JOptionPane.showMessageDialog(this, "Thêm mới Hóa đơn thành công!");//đưa ra thông báo khi thực hiện thành công
        }
        else{
            JOptionPane.showMessageDialog(this, "Số hóa đơn phải nhập số!", "Thông báo", JOptionPane.WARNING_MESSAGE); 
        }
    }
    private void banhang(){
        for(int i = 0;i < tbl_data.getRowCount(); i++){
            Dm_khohang slkho = new Dm_khohang();
            slkho.setSL_tonkho(Integer.parseInt(tbl_data.getValueAt(i, 3).toString()));
            slkho.setMa_hang(tbl_data.getValueAt(i, 0).toString());

            DAOnghiepvu.Xoahang(slkho);
        }      
    }    
    private void ctietX(){
        Nghiepvu nghiepvu = new Nghiepvu();
        boolean isNumeric = true;
        for (int i = 0; i < tbl_data.getRowCount() ; i++) {
            try {
                int num = Integer.parseInt(tbl_data.getValueAt(i, 3).toString());
//                int num2=Integer.parseInt(txt_mahoadon.getText());
                isNumeric = true;

             } catch (NumberFormatException e) {
                isNumeric = false;
            }
            if (isNumeric) {
                try {
                    Connection conn = MySQLConnUtils.getMySQLConnection();
                    PreparedStatement stm = conn.prepareStatement("SELECT * FROM `hoadonxuat` ORDER BY hoadonxuat.Ma_HDX DESC LIMIT 0,1");
                    ResultSet rs = stm.executeQuery();

                    while (rs.next()) {
                        nghiepvu.setMa_HDX(rs.getInt("Ma_HDX"));
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DAONghiepvu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DAONghiepvu.class.getName()).log(Level.SEVERE, null, ex);
                }
                nghiepvu.setSoluongX(Integer.parseInt(tbl_data.getValueAt(i, 3).toString()));
                nghiepvu.setGiam_gia(Integer.parseInt(tbl_data.getValueAt(i, 4).toString()));
                nghiepvu.setMa_hang(tbl_data.getValueAt(i , 0).toString());
                
                DAOnghiepvu.ThemCTxuat(nghiepvu); 
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Số hóa đơn phải nhập số!", "Thông báo", JOptionPane.WARNING_MESSAGE); 
            }
        }
    }    
    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        hoadonX();
        banhang();
        ctietX();
        reset();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        if(tbl_data.getSelectedRow() >= 0){
            model.removeRow(tbl_data.getSelectedRow());
        } else{
            JOptionPane.showMessageDialog(this, "Không thể xóa.");
        }
    }//GEN-LAST:event_jPanel12MouseClicked
    private void default_mahang(){
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            String sql = "SELECT * FROM hang,chitietnhap,chitietkho "
                    + "WHERE hang.Ma_hang=chitietnhap.Ma_hang AND hang.Ma_hang=chitietkho.Ma_hang "
                    + "AND hang.Ma_hang='"+cb_mahang.getSelectedItem().toString()+"'";
            
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                txt_tenhang.setText(rs.getString("Ten_hang"));
                txt_tonkho.setText(rs.getString("SL_tonkho"));
                txt_dongia.setText(rs.getString("Giaban"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }  
    }
    private void cb_mahangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mahangActionPerformed
        default_mahang();
    }//GEN-LAST:event_cb_mahangActionPerformed
    private void default_manv(){
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            String sql = "SELECT * FROM nhanvien WHERE Ma_NV='"+cb_manv.getSelectedItem().toString()+"'";
            
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                txt_tennv.setText(rs.getString("Hoten"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    private void cb_manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_manvActionPerformed
         default_manv();
    }//GEN-LAST:event_cb_manvActionPerformed
    private void default_makh(){
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            String sql = "SELECT * FROM khachhang WHERE Ma_KH='"+cb_makh.getSelectedItem().toString()+"'";
            
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                txt_tenkh.setText(rs.getString("Ten_KH"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    private void cb_makhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_makhActionPerformed
            default_makh();
    }//GEN-LAST:event_cb_makhActionPerformed

    private void tbl_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMousePressed
        int row=tbl_data.getSelectedRow();
        if(row==tbl_data.getRowCount()){
//            txt_mahoadon.setText("");
            default_mahang();
            default_makh();
            default_manv();
        }
        else{
            cb_mahang.setSelectedItem(tbl_data.getValueAt(row, 0).toString());
            txt_tenhang.setText(tbl_data.getValueAt(row, 1).toString());
            txt_dongia.setText(tbl_data.getValueAt(row, 2).toString());
            txt_sluong.setText(tbl_data.getValueAt(row, 3).toString());
            txt_giamgia.setText(tbl_data.getValueAt(row, 4).toString());
        } 
    }//GEN-LAST:event_tbl_dataMousePressed

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        new Frame.In_hoadonbanhang().setVisible(true);
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        cb_mahang();
    }//GEN-LAST:event_jLabel2MouseClicked
    private void cb_mahang(){
        String sql = "SELECT * FROM hang";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_mahang.addItem(rs.getString("Ma_hang"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    private void cb_makh(){
        String sql = "SELECT * FROM khachhang";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_makh.addItem(rs.getString("Ma_KH"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    private void cb_manv(){
        String sql = "SELECT * FROM nhanvien";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_manv.addItem(rs.getString("Ma_NV"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINghiepvu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINghiepvu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINghiepvu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINghiepvu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINghiepvu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnbanhang;
    private javax.swing.JPanel btnhoadonban;
    private javax.swing.JPanel btnhoadonnhap;
    private javax.swing.JPanel btnhoadontra;
    private javax.swing.JPanel btnnhaphang;
    private javax.swing.JPanel btntrahang;
    private javax.swing.JComboBox cb_mahang;
    private javax.swing.JComboBox cb_makh;
    private javax.swing.JComboBox cb_manv;
    private com.toedter.calendar.JDateChooser cbngayxuat;
    private javax.swing.JPanel ind2;
    private javax.swing.JPanel ind3;
    private javax.swing.JPanel ind4;
    private javax.swing.JPanel ind5;
    private javax.swing.JPanel ind7;
    private javax.swing.JPanel ind8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_tongtien;
    private javax.swing.JLabel lbexit;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_datra;
    private javax.swing.JTextField txt_dongia;
    private javax.swing.JTextField txt_giamgia;
    private javax.swing.JTextField txt_sluong;
    private javax.swing.JTextField txt_tenhang;
    private javax.swing.JTextField txt_tenkh;
    private javax.swing.JTextField txt_tennv;
    private javax.swing.JTextField txt_tonkho;
    // End of variables declaration//GEN-END:variables
}
