
package Frame;

import DAOFrame.DAODanhmuc_khachhang;
import DBConnect.MySQLConnUtils;
import OBJFrame.Dm_khachhang;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Danhmuc_khachhang extends javax.swing.JPanel {
    DAOFrame.DAODanhmuc_khachhang DAOkhachhang=new DAODanhmuc_khachhang();
    public Danhmuc_khachhang() {
        initComponents();
        loadData();
    }
    Connection dbConnection = null;
    Statement statement = null;
    public void loadData() {
    // Clear table
    tbl_data.setModel(new DefaultTableModel());
    // Model for Table
    DefaultTableModel model = new DefaultTableModel() {
        public Class<?> getColumnClass(int column) {
            switch (column) {
            case 0:
                return String.class;
            case 1:
                return String.class;
            case 2:
                return String.class;
            case 3:
                return String.class;
            case 4:
                return String.class;
            case 5:
                return String.class;
            case 6:
                return Boolean.class;
            default:
                return String.class;        
          }
        }
    };
    tbl_data.setModel(model);

    // Add Column
    model.addColumn("STT");
    model.addColumn("Mã Khách Hàng");
    model.addColumn("Tên Khách Hàng");
    model.addColumn("Địa Chỉ");
    model.addColumn("SĐT");
    model.addColumn("Nợ Đầu");
    model.addColumn("Chọn");
    
    String sql = "SELECT * FROM  khachhang";
    try {
        dbConnection = MySQLConnUtils.getMySQLConnection();
        statement = dbConnection.createStatement();
        ResultSet rs = statement.executeQuery(sql);

        int row = 0;
        while ((rs != null) && (rs.next())) {
            model.addRow(new Object[0]);
            model.setValueAt(row+1, row, 0);
            model.setValueAt(rs.getString("Ma_KH"), row, 1);
            model.setValueAt(rs.getString("Ten_KH"), row, 2);
            model.setValueAt(rs.getString("Diachi"), row, 3);
            model.setValueAt("0"+rs.getString("SDT"), row, 4);
            model.setValueAt(rs.getString("No_dau"), row, 5);
            
                
            model.setValueAt(false, row, 6); // Checkbox
            
            row++;
            }
        } catch (Exception e) {
            e.printStackTrace();
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        txt_tenkh = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 120, 215));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_dataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 830, 300));

        txt_tenkh.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tenkh.setForeground(new java.awt.Color(0, 120, 215));
        add(txt_tenkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 30));

        txt_diachi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_diachi.setForeground(new java.awt.Color(0, 120, 215));
        add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 200, 30));

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_sdt.setForeground(new java.awt.Color(0, 120, 215));
        add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 200, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 120, 215));
        jLabel3.setText("Tên Khách Hàng");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 120, 215));
        jLabel4.setText("Số Điện Thoại");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 120, 215));
        jLabel5.setText("Địa Chỉ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 120, 215));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thêm Khách Hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 160, 40));

        jPanel3.setBackground(new java.awt.Color(0, 120, 215));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Xóa Khách Hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 160, -1));

        jPanel4.setBackground(new java.awt.Color(0, 120, 215));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sửa thông tin KH");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        txt_diachi.setText("");
        txt_sdt.setText("");
        txt_tenkh.setText("");
    }
    private void tbl_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMousePressed
        int row = tbl_data.getSelectedRow();
        String ma_kh = tbl_data.getValueAt(row, 1).toString();
        Dm_khachhang khachhang = new Dm_khachhang();
        khachhang = DAOkhachhang.TimKhachhang(ma_kh);
        txt_tenkh.setText(khachhang.getTen_KH());
        txt_sdt.setText(khachhang.getSDT().toString());
        txt_diachi.setText(khachhang.getDiachi());
    }//GEN-LAST:event_tbl_dataMousePressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       boolean isNumeric = true;
        
        try {
            int num = Integer.parseInt(txt_sdt.getText());
            isNumeric = true;

        } catch (NumberFormatException e) {
            isNumeric = false;
        }
        if (isNumeric) { 
            Dm_khachhang khachhang = new Dm_khachhang();
            khachhang.setTen_KH(txt_tenkh.getText());
            khachhang.setDiachi(txt_diachi.getText());
            khachhang.setSDT(Integer.parseInt(txt_sdt.getText()));

                if (txt_sdt.getText().equals("") || txt_tenkh.getText().equals("")) {
                    //nếu 1 số ô trong đó để rỗng sẽ đưa ra thông báo
                    JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                } else {
                    //ngược lại thực hiện lấy dữ liệu trong các ô để đưa vào CSDL
                    DAOkhachhang.ThemKhachhang(khachhang);

                    JOptionPane.showMessageDialog(this, "Thêm mới Khách hàng thành công!");//đưa ra thông báo khi thực hiện thành công
                    loadData();//load lại form
                    reset();//xóa dữ liệu trong các ô text
                }

            
        }else{
            JOptionPane.showMessageDialog(null,"Số Điện Thoại của Khách hàng phải nhập số!");
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        Integer confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa các khách hàng này không?", "Xóa", 2);
        //khi người dùng ấn đồng ý
        if (confirm == JOptionPane.YES_OPTION) {

            for (int i = 0; i < tbl_data.getRowCount(); i++) {
                Boolean chkDel = Boolean.valueOf(tbl_data.getValueAt(i, 6).toString()); // Checked
                if(chkDel){
                    String kh = tbl_data.getValueAt(i, 1).toString();

                    DAOkhachhang.XoaKhachhang(kh); // Delete Data
                    reset();
                    
                }
            }
            JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công!");
            loadData(); // Reload Table
        }else{
            reset();
        }

   
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        Dm_khachhang khachhang = new Dm_khachhang();
        khachhang.setMa_KH(Integer.parseInt(tbl_data.getValueAt(tbl_data.getSelectedRow(), 1).toString()));
        khachhang.setTen_KH(txt_tenkh.getText());
        khachhang.setDiachi(txt_diachi.getText());
        khachhang.setSDT(Integer.parseInt(txt_sdt.getText()));

        DAOkhachhang.SuaKhachhang(khachhang);

        JOptionPane.showMessageDialog(this, "Cập nhật thông tin khách hàng thành công!");//đưa ra thông báo khi thực hiện thành công
        loadData();//load lại form
        reset();
    }//GEN-LAST:event_jPanel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenkh;
    // End of variables declaration//GEN-END:variables
}
