
package Frame;

import DAOFrame.DAONghiepvu_trahang;
import DAOGUI.DAONghiepvu;
import DBConnect.MySQLConnUtils;
import OBJFrame.Dm_khohang;
import OBJFrame.Nv_trahang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class Nghiepvu_trahang extends javax.swing.JPanel {
    DAOFrame.DAONghiepvu_trahang DAOtrahang = new DAONghiepvu_trahang();
    public Nghiepvu_trahang() {
        initComponents();
        loadData();
        table();
        ngayhientai();
        cb_mahang();
        cb_manhacc();
        cb_manv();
    }

    Connection dbConnection = null;
    Statement statement = null;
    public void loadData() {
        // Clear table
        tbl_data.setModel(new DefaultTableModel());
        // Model for Table
        DefaultTableModel model = new DefaultTableModel() {
            public Class<?> getColumnClass(int column) {
                switch (column) {
                case 0:
                    return String.class;
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return String.class;

                default:
                    return String.class;        
              }
            }
        };
        tbl_data.setModel(model);

        // Add Column
        model.addColumn("Mã hàng");
        model.addColumn("Tên hàng");
        model.addColumn("Đơn giá");
        model.addColumn("Số lượng");
        model.addColumn("Thành tiền");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_manv = new javax.swing.JComboBox();
        txt_tennv = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cb_manhacc = new javax.swing.JComboBox();
        txt_nhacc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cb_mahang = new javax.swing.JComboBox();
        txt_tenhang = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_sluong = new javax.swing.JTextField();
        txt_dongia = new javax.swing.JTextField();
        lb_tongtien = new javax.swing.JLabel();
        txt_tonkho = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_datra = new javax.swing.JTextField();
        cbngaytra = new com.toedter.calendar.JDateChooser();
        jPanel13 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(154, 0, 137));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TRẢ HÀNG");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 80));

        jLabel15.setBackground(new java.awt.Color(154, 0, 137));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(154, 0, 137));
        jLabel15.setText("Thông tin chung");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel17.setBackground(new java.awt.Color(154, 0, 137));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(154, 0, 137));
        jLabel17.setText("Ngày bán");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jLabel18.setBackground(new java.awt.Color(154, 0, 137));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(154, 0, 137));
        jLabel18.setText("Mã nhân viên");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel19.setBackground(new java.awt.Color(154, 0, 137));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(154, 0, 137));
        jLabel19.setText("Tên nhân viên");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        cb_manv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_manv.setForeground(new java.awt.Color(154, 0, 137));
        cb_manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_manvActionPerformed(evt);
            }
        });
        add(cb_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, 30));

        txt_tennv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tennv.setForeground(new java.awt.Color(154, 0, 137));
        add(txt_tennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, 30));

        jLabel20.setBackground(new java.awt.Color(154, 0, 137));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(154, 0, 137));
        jLabel20.setText("Mã nhà cung cấp");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jLabel21.setBackground(new java.awt.Color(154, 0, 137));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(154, 0, 137));
        jLabel21.setText("Tên nhà cung cấp");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        cb_manhacc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_manhacc.setForeground(new java.awt.Color(154, 0, 137));
        cb_manhacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_manhaccActionPerformed(evt);
            }
        });
        add(cb_manhacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 130, 30));

        txt_nhacc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_nhacc.setForeground(new java.awt.Color(154, 0, 137));
        add(txt_nhacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 130, 30));

        jLabel14.setBackground(new java.awt.Color(154, 0, 137));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(154, 0, 137));
        jLabel14.setText("Thông tin các mặt hàng");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel26.setBackground(new java.awt.Color(154, 0, 137));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(154, 0, 137));
        jLabel26.setText("Mã hàng");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel27.setBackground(new java.awt.Color(154, 0, 137));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(154, 0, 137));
        jLabel27.setText("Tên hàng");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        cb_mahang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_mahang.setForeground(new java.awt.Color(154, 0, 137));
        cb_mahang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mahangActionPerformed(evt);
            }
        });
        add(cb_mahang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 150, 30));

        txt_tenhang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tenhang.setForeground(new java.awt.Color(154, 0, 137));
        add(txt_tenhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 180, 30));

        jLabel28.setBackground(new java.awt.Color(154, 0, 137));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(154, 0, 137));
        jLabel28.setText("Số lượng");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel30.setBackground(new java.awt.Color(154, 0, 137));
        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(154, 0, 137));
        jLabel30.setText("Đơn giá");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        txt_sluong.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_sluong.setForeground(new java.awt.Color(154, 0, 137));
        add(txt_sluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 140, 30));

        txt_dongia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_dongia.setForeground(new java.awt.Color(154, 0, 137));
        add(txt_dongia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 140, 30));

        lb_tongtien.setBackground(new java.awt.Color(154, 0, 137));
        lb_tongtien.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lb_tongtien.setForeground(new java.awt.Color(154, 0, 137));
        add(lb_tongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 160, 20));

        txt_tonkho.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tonkho.setForeground(new java.awt.Color(154, 0, 137));
        add(txt_tonkho, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 130, 30));

        jPanel10.setBackground(new java.awt.Color(154, 0, 137));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Thêm hàng trả");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 130, -1));

        jPanel12.setBackground(new java.awt.Color(154, 0, 137));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Xóa hàng");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel32)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addContainerGap())
        );

        add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        jPanel11.setBackground(new java.awt.Color(154, 0, 137));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Lập hóa đơn");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel24)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 130, -1));

        tbl_data.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbl_data.setForeground(new java.awt.Color(154, 0, 137));
        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_data.setSelectionBackground(new java.awt.Color(154, 0, 137));
        jScrollPane1.setViewportView(tbl_data);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 850, 260));

        jLabel31.setBackground(new java.awt.Color(154, 0, 137));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(154, 0, 137));
        jLabel31.setText("Đã trả");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLabel33.setBackground(new java.awt.Color(154, 0, 137));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(154, 0, 137));
        jLabel33.setText("Tổng tiền:");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, -1));

        jLabel34.setBackground(new java.awt.Color(154, 0, 137));
        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(154, 0, 137));
        jLabel34.setText("Tồn kho");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        txt_datra.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_datra.setForeground(new java.awt.Color(154, 0, 137));
        txt_datra.setText("0");
        add(txt_datra, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 130, 30));

        cbngaytra.setBackground(new java.awt.Color(255, 255, 255));
        cbngaytra.setForeground(new java.awt.Color(154, 0, 137));
        cbngaytra.setDateFormatString("yyyy-MM-dd");
        cbngaytra.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(cbngaytra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 120, 30));

        jPanel13.setBackground(new java.awt.Color(154, 0, 137));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("In hóa đơn");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel35)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Synchronize_20px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, 30));
    }// </editor-fold>//GEN-END:initComponents
    private void table(){
        for(int i=0;i<5;i++){
            TableColumn column = null;
            column=tbl_data.getColumnModel().getColumn(i);
            if(i==0)
                column.setPreferredWidth(100);
            if(i==1)
                column.setPreferredWidth(300);
        }
    }
    private void ngayhientai(){
        cbngaytra.setDateFormatString("dd/MM/yyyy");
        GregorianCalendar calendar = new GregorianCalendar();
        int ngay=calendar.get(Calendar.DATE);
        int thang=calendar.get(Calendar.MONTH)+1;
        int nam=calendar.get(Calendar.YEAR);
        String ngaythang=nam+"-"+thang+"-"+ngay;
        try {
            Date date= new SimpleDateFormat("yyyy-MM-dd").parse(ngaythang);
            cbngaytra.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Nghiepvu_trahang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void default_mahang(){
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            String sql = "SELECT * FROM hang,chitietnhap,chitietkho "
                    + "WHERE hang.Ma_hang=chitietnhap.Ma_hang AND hang.Ma_hang=chitietkho.Ma_hang "
                    + "AND hang.Ma_hang='"+cb_mahang.getSelectedItem().toString()+"'";
            
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                txt_tenhang.setText(rs.getString("Ten_hang"));
                txt_tonkho.setText(rs.getString("SL_tonkho"));
                txt_dongia.setText(rs.getString("Giaban"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }  
    }
    private void default_manv(){
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            String sql = "SELECT * FROM nhanvien WHERE Ma_NV='"+cb_manv.getSelectedItem().toString()+"'";
            
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                txt_tennv.setText(rs.getString("Hoten"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    private void default_manhacc(){
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            String sql = "SELECT * FROM nhacungcap WHERE Ma_NCC='"+cb_manhacc.getSelectedItem().toString()+"'";
            
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                txt_nhacc.setText(rs.getString("Ten_NCC"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        } 
    }
    private void cb_mahang(){
        String sql = "SELECT * FROM hang";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_mahang.addItem(rs.getString("Ma_hang"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    private void cb_manhacc(){
        String sql = "SELECT * FROM nhacungcap";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_manhacc.addItem(rs.getString("Ma_NCC"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    private void cb_manv(){
        String sql = "SELECT * FROM nhanvien";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_manv.addItem(rs.getString("Ma_NV"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }    
    private void reset(){
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        model.setRowCount(0);
        ngayhientai();
        cb_manv.setSelectedIndex(0);
        cb_mahang.setSelectedIndex(0);
        cb_manhacc.setSelectedIndex(0);
        default_mahang();
        default_manv();
        default_manhacc();
        txt_sluong.setText("");
        lb_tongtien.setText("");
    }
    private void cb_manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_manvActionPerformed
        default_manv();
    }//GEN-LAST:event_cb_manvActionPerformed

    private void cb_manhaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_manhaccActionPerformed
        default_manhacc();
    }//GEN-LAST:event_cb_manhaccActionPerformed

    private void cb_mahangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mahangActionPerformed
        default_mahang();
    }//GEN-LAST:event_cb_mahangActionPerformed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        int soluongtra=0;
        if(Integer.parseInt(txt_sluong.getText())>Integer.parseInt(txt_tonkho.getText())){
            JOptionPane.showMessageDialog(this, "Bạn không thể trả hàng quá số lượng tồn kho!" , "Thông báo", JOptionPane.WARNING_MESSAGE);
                txt_sluong.setText("");
        }
        else{
//            for(int i=0;i<tbl_data.getRowCount();i++){
//                if(Integer.parseInt(cb_mahang.getSelectedItem().toString())==Integer.parseInt(tbl_data.getValueAt(i, 0).toString())){
//                    soluongtra=soluongtra+Integer.parseInt(tbl_data.getValueAt(i, 3).toString())+Integer.parseInt(txt_sluong.getText());
//                }
//
//            }
            if (txt_sluong.getText().equals("") || txt_tenhang.getText().equals("")|| txt_tonkho.getText().equals("")) {
                    //nếu 1 số ô trong đó để rỗng sẽ đưa ra thông báo
                    JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }else {
                if(soluongtra>Integer.parseInt(txt_tonkho.getText())){
                    JOptionPane.showMessageDialog(this, "Bạn không thể trả hàng quá số lượng tồn kho!" , "Thông báo", JOptionPane.WARNING_MESSAGE);
                    txt_sluong.setText("");
                }
                else{
                    int gia=Integer.parseInt(txt_dongia.getText())*Integer.parseInt(txt_sluong.getText());

                    model.addRow(new Object[]{cb_mahang.getSelectedItem().toString(),txt_tenhang.getText(), txt_dongia.getText(),
                    txt_sluong.getText(),gia});
                    txt_dongia.setText("");
                    txt_tenhang.setText("");
                    txt_tonkho.setText("");
                    txt_sluong.setText("");
                    cb_mahang.setSelectedIndex(0);
                    default_mahang();
                    int tongtien=0;
                    for(int i = 0;i<tbl_data.getRowCount();i++){
                        tongtien=tongtien+Integer.parseInt(tbl_data.getValueAt(i, 4).toString());
                    }
                    Locale localeVN = new Locale("vi", "VN");
                    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
                    String tien = currencyVN.format(tongtien);
                    lb_tongtien.setText(tien);

                }
            }       
        }
        
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        if(tbl_data.getSelectedRow() >= 0){
            model.removeRow(tbl_data.getSelectedRow());
        } else{
            JOptionPane.showMessageDialog(this, "Không thể xóa.");
        }
    }//GEN-LAST:event_jPanel12MouseClicked
    private void hoadonT(){
        Nv_trahang trahang = new Nv_trahang();
        
        Date date = cbngaytra.getDate();
        String dateInput = new SimpleDateFormat("yyyy-MM-dd").format(date);
        boolean isNumeric = true;
        
        try {
            int num = Integer.parseInt(txt_datra.getText());

            if(num>=0){
                isNumeric = true;
            }
            else{
                JOptionPane.showMessageDialog(this, "Số tiền đã trả phải >=0");
            }
            isNumeric = true;

         } catch (NumberFormatException e) {
            isNumeric = false;
        }

        if (isNumeric) {   
            int tongtien=0;
                for(int i = 0;i<tbl_data.getRowCount();i++){
                    tongtien=tongtien+Integer.parseInt(tbl_data.getValueAt(i, 4).toString());
                }

            trahang.setNgay_tra(dateInput);
            trahang.setDa_tra(Integer.parseInt(txt_datra.getText()));
            trahang.setMa_NV(cb_manv.getSelectedItem().toString());
            trahang.setMa_NCC(cb_manhacc.getSelectedItem().toString());
            trahang.setThanhtientra(tongtien);
            DAOtrahang.ThemHoadonT(trahang); 

            JOptionPane.showMessageDialog(this, "Thêm mới Hóa đơn thành công!");//đưa ra thông báo khi thực hiện thành công
        }
        else{
            JOptionPane.showMessageDialog(this, "Số hóa đơn hoặc số tiền trả phải nhập số!", "Thông báo", JOptionPane.WARNING_MESSAGE); 
        } 
    }      
    
    private void trahang(){
        for(int i = 0;i < tbl_data.getRowCount(); i++){
            Dm_khohang trahang = new Dm_khohang();
            trahang.setSL_tonkho(Integer.parseInt(tbl_data.getValueAt(i, 3).toString()));
            trahang.setMa_hang(tbl_data.getValueAt(i, 0).toString());

            DAOtrahang.Xoahang(trahang);
        }      
    }    
    private void ctietT(){
        Nv_trahang trahang = new Nv_trahang();
        boolean isNumeric = true;
        for (int i = 0; i < tbl_data.getRowCount() ; i++) {
            try {
                int num = Integer.parseInt(tbl_data.getValueAt(i, 3).toString());
                isNumeric = true;

             } catch (NumberFormatException e) {
                isNumeric = false;
            }
            if (isNumeric) {
                try {
                    Connection conn = MySQLConnUtils.getMySQLConnection();
                    PreparedStatement stm = conn.prepareStatement("SELECT * FROM `hoadontra` ORDER BY hoadontra.Ma_HDT DESC LIMIT 0,1");
                    ResultSet rs = stm.executeQuery();

                    while (rs.next()) {
                        trahang.setMa_HDT(rs.getInt("Ma_HDT"));
                    }
                } catch (Exception e){
                    
                }
                trahang.setMa_hang(tbl_data.getValueAt(i , 0).toString());
                trahang.setSoluongT(Integer.parseInt(tbl_data.getValueAt(i, 3).toString()));
        
                DAOtrahang.ThemCTtra(trahang); 
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Số hóa đơn phải nhập số!", "Thông báo", JOptionPane.WARNING_MESSAGE); 
            }
        }
    }     
    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        hoadonT();
        trahang();
        ctietT();
        reset();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        new Frame.In_hoadontrahang().setVisible(true);
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        cb_mahang();
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_mahang;
    private javax.swing.JComboBox cb_manhacc;
    private javax.swing.JComboBox cb_manv;
    private com.toedter.calendar.JDateChooser cbngaytra;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_tongtien;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_datra;
    private javax.swing.JTextField txt_dongia;
    private javax.swing.JTextField txt_nhacc;
    private javax.swing.JTextField txt_sluong;
    private javax.swing.JTextField txt_tenhang;
    private javax.swing.JTextField txt_tennv;
    private javax.swing.JTextField txt_tonkho;
    // End of variables declaration//GEN-END:variables
}
