
package Frame;

import DAOFrame.DAODanhmuc_khohang;
import DAOFrame.DAONghiepvu_nhaphang;
import DBConnect.MySQLConnUtils;
import OBJFrame.Dm_khohang;
import OBJFrame.Nv_nhaphang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Nghiepvu_nhaphang extends javax.swing.JPanel {
    DAOFrame.DAONghiepvu_nhaphang DAOnhaphang = new DAONghiepvu_nhaphang();
    DAOFrame.DAODanhmuc_khohang DAOkhohang = new DAODanhmuc_khohang();
    public Nghiepvu_nhaphang() {
        initComponents();
        cbloaihang();
        cbdvt();
        cbnhacc();
        cbma_kho();
        manv();
        loadData();
        ngayhientai();
    }
    Connection dbConnection = null;
    Statement statement = null;
    
    public void loadData() {
        // Clear table
        tbl_data.setModel(new DefaultTableModel());
        // Model for Table
        DefaultTableModel model = new DefaultTableModel() {
            public Class<?> getColumnClass(int column) {
                switch (column) {
                case 0:
                    return String.class;
                case 1:
                    return String.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return String.class;
                case 5:
                    return String.class;   
                case 6:
                    return String.class;
                default:
                    return String.class;        
              }
            }
        };
        tbl_data.setModel(model);

        // Add Column
        model.addColumn("Mã hàng");
        model.addColumn("Tên hàng");
        model.addColumn("Giá bán");
        model.addColumn("Giá nhập");
        model.addColumn("Mã DVT");
        model.addColumn("Mã loại hàng");
        model.addColumn("Số lượng");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sluong = new javax.swing.JSpinner();
        cb_manv = new javax.swing.JComboBox();
        txt_mahang = new javax.swing.JTextField();
        cb_tenlhang = new javax.swing.JComboBox();
        txt_tenhang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cb_dvt = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txt_gianhap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_giaban = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cb_nhacc = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txt_chietkhau = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_datra = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cb_makho = new javax.swing.JComboBox();
        cbngaynhap = new com.toedter.calendar.JDateChooser();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_tennv = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lbtongcong = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbchietkhau = new javax.swing.JLabel();
        lbthanhtien = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_data.setForeground(new java.awt.Color(154, 0, 137));
        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null ", "null  ", "null ", "null "
            }
        ));
        tbl_data.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_data.setSelectionBackground(new java.awt.Color(154, 0, 137));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_dataMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_data);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 347, 870, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 0, 137));
        jLabel1.setText("Đã Trả");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(154, 0, 137));
        jLabel2.setText("Mã hàng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(154, 0, 137));
        jLabel3.setText("Tên nhân viên");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(154, 0, 137));
        jLabel4.setText("Mã,Tên lhang");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(154, 0, 137));
        jLabel5.setText("Số lượng nhập");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        sluong.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(sluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 80, 30));

        cb_manv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_manv.setForeground(new java.awt.Color(154, 0, 137));
        cb_manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_manvActionPerformed(evt);
            }
        });
        jPanel1.add(cb_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, 30));

        txt_mahang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_mahang.setForeground(new java.awt.Color(154, 0, 137));
        jPanel1.add(txt_mahang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 140, 30));

        cb_tenlhang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_tenlhang.setForeground(new java.awt.Color(154, 0, 137));
        jPanel1.add(cb_tenlhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 130, 30));

        txt_tenhang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tenhang.setForeground(new java.awt.Color(154, 0, 137));
        jPanel1.add(txt_tenhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, 30));

        jPanel2.setBackground(new java.awt.Color(154, 0, 137));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thêm hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 130, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(154, 0, 137));
        jLabel8.setText("Tên hàng");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jPanel3.setBackground(new java.awt.Color(154, 0, 137));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Xóa hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 130, -1));

        cb_dvt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_dvt.setForeground(new java.awt.Color(154, 0, 137));
        jPanel1.add(cb_dvt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 140, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(154, 0, 137));
        jLabel10.setText("Mã,Tên NCC");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        txt_gianhap.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_gianhap.setForeground(new java.awt.Color(154, 0, 137));
        txt_gianhap.setText("0");
        jPanel1.add(txt_gianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 140, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(154, 0, 137));
        jLabel11.setText("Giá bán");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        txt_giaban.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_giaban.setForeground(new java.awt.Color(154, 0, 137));
        txt_giaban.setText("0");
        jPanel1.add(txt_giaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 130, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(154, 0, 137));
        jLabel12.setText("Giá nhập");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jPanel4.setBackground(new java.awt.Color(154, 0, 137));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tạo Hóa Đơn");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 130, -1));

        cb_nhacc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_nhacc.setForeground(new java.awt.Color(154, 0, 137));
        jPanel1.add(cb_nhacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 140, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(154, 0, 137));
        jLabel17.setText("Mã,Tên đvt");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        txt_chietkhau.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_chietkhau.setForeground(new java.awt.Color(154, 0, 137));
        txt_chietkhau.setText("0");
        jPanel1.add(txt_chietkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 130, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(154, 0, 137));
        jLabel18.setText("Chiết Khấu(%)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        txt_datra.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_datra.setForeground(new java.awt.Color(154, 0, 137));
        txt_datra.setText("0");
        jPanel1.add(txt_datra, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 140, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(154, 0, 137));
        jLabel20.setText("Mã ,Tên Kho");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jPanel6.setBackground(new java.awt.Color(154, 0, 137));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NHẬP HÀNG");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 80));

        jLabel21.setBackground(new java.awt.Color(154, 0, 137));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(154, 0, 137));
        jLabel21.setText("Thông tin hàng");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel24.setBackground(new java.awt.Color(154, 0, 137));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(154, 0, 137));
        jLabel24.setText("Thông tin chung");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(154, 0, 137));
        jLabel25.setText("Ngày nhập");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        cb_makho.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cb_makho.setForeground(new java.awt.Color(154, 0, 137));
        jPanel1.add(cb_makho, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 140, 30));

        cbngaynhap.setBackground(new java.awt.Color(255, 255, 255));
        cbngaynhap.setForeground(new java.awt.Color(154, 0, 137));
        cbngaynhap.setDateFormatString("yyyy-MM-dd");
        cbngaynhap.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(cbngaynhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 130, 30));

        jPanel13.setBackground(new java.awt.Color(154, 0, 137));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("In hóa đơn");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel34)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 130, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(154, 0, 137));
        jLabel9.setText(" Mã nhân viên");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txt_tennv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_tennv.setForeground(new java.awt.Color(154, 0, 137));
        jPanel1.add(txt_tennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(154, 0, 137));
        jLabel16.setText("Tổng cộng:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, -1, -1));

        lbtongcong.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbtongcong.setForeground(new java.awt.Color(154, 0, 137));
        add(lbtongcong, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, 110, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(154, 0, 137));
        jLabel22.setText("Thành tiền:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(154, 0, 137));
        jLabel23.setText("Chiết khấu:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        lbchietkhau.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbchietkhau.setForeground(new java.awt.Color(154, 0, 137));
        add(lbchietkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 60, 20));

        lbthanhtien.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbthanhtien.setForeground(new java.awt.Color(154, 0, 137));
        add(lbthanhtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 110, 20));
    }// </editor-fold>//GEN-END:initComponents
    private void ngayhientai(){
        cbngaynhap.setDateFormatString("dd/MM/yyyy");
        GregorianCalendar calendar = new GregorianCalendar();
        int ngay=calendar.get(Calendar.DATE);
        int thang=calendar.get(Calendar.MONTH)+1;
        int nam=calendar.get(Calendar.YEAR);
        String ngaythang=nam+"-"+thang+"-"+ngay;
        try {
            Date date= new SimpleDateFormat("yyyy-MM-dd").parse(ngaythang);
            cbngaynhap.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Nghiepvu_hoadonnhaphang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void cbloaihang(){
        String sql = "SELECT * FROM loaihang";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_tenlhang.addItem(rs.getString("Ma_loaihang")+","+rs.getString("Ten_loaihang"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void cbdvt(){
            String sql = "SELECT * FROM donvitinh";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_dvt.addItem(rs.getString("Ma_dvt")+","+rs.getString("Ten_dvt"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    private void cbnhacc(){
            String sql = "SELECT * FROM nhacungcap";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_nhacc.addItem(rs.getString("Ma_NCC")+","+rs.getString("Ten_NCC"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    private void cbma_kho(){
            String sql = "SELECT * FROM khohang";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_makho.addItem(rs.getString("Ma_khohang")+","+rs.getString("Ten_khohang"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    private void manv(){
            String sql = "SELECT * FROM nhanvien";
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                cb_manv.addItem(rs.getString("Ma_NV"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        }    
    }
    private void tbl_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMousePressed
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        int row=tbl_data.getSelectedRow();
        if(row==tbl_data.getRowCount()){
            txt_mahang.setText("");
            txt_tenhang.setText("");
            txt_giaban.setText("0");
            txt_gianhap.setText("0");
            sluong.setValue(0);
            cb_dvt.setSelectedIndex(0);
            cb_nhacc.setSelectedIndex(0);
        }
        else{
            txt_mahang.setText(tbl_data.getValueAt(row, 0).toString());
            txt_tenhang.setText(tbl_data.getValueAt(row, 1).toString());
            txt_giaban.setText(tbl_data.getValueAt(row, 2).toString());
            txt_gianhap.setText(tbl_data.getValueAt(row, 3).toString());
            cb_dvt.setSelectedItem(tbl_data.getValueAt(row, 4).toString());
            cb_tenlhang.setSelectedItem(tbl_data.getValueAt(row, 5).toString());
            sluong.setValue(tbl_data.getValueAt(row, 6).toString());
            try {
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(row, 9));
                cbngaynhap.setDate(date);
            } catch (Exception ex) {

            }
        } 
    }//GEN-LAST:event_tbl_dataMousePressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();

        if (txt_mahang.getText().equals("") || txt_tenhang.getText().equals("")|| txt_giaban.getText().equals("")
            || txt_gianhap.getText().equals("")) {
            //nếu 1 số ô trong đó để rỗng sẽ đưa ra thông báo
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }else {
            
            Date date = cbngaynhap.getDate();
            String dateInput = new SimpleDateFormat("yyyy-MM-dd").format(date);
            String s = new String();
            int i,j,k,l;
            for(i=0;i<=cb_nhacc.getSelectedItem().toString().length();i++){            
                    s=cb_nhacc.getSelectedItem().toString().substring(i,i+1);
                    if(s.equals(",")) break;                                              
            }
            for(j=0;j<=cb_dvt.getSelectedItem().toString().length();j++){         
                    s=cb_dvt.getSelectedItem().toString().substring(j,j+1);
                    if(s.equals(",")) break;                                              
            }
            for(k=0;k<=cb_tenlhang.getSelectedItem().toString().length();k++){
                    s=cb_tenlhang.getSelectedItem().toString().substring(k,k+1);
                    if(s.equals(",")) break;                                             
            }

            model.addRow(new Object[]{txt_mahang.getText(),txt_tenhang.getText(), txt_giaban.getText(),txt_gianhap.getText(),
            cb_dvt.getSelectedItem().toString().substring(0,j),cb_tenlhang.getSelectedItem().toString().substring(0,k),sluong.getValue().toString()});
            txt_mahang.setText("");
            txt_tenhang.setText("");
            txt_giaban.setText("0");
            txt_gianhap.setText("0");
            sluong.setValue(0);
            cb_dvt.setSelectedIndex(0);
            cb_nhacc.setSelectedIndex(0);
            cb_tenlhang.setSelectedIndex(0);
            int thanhtien=0,gia=0;
            for(int p=0;p<tbl_data.getRowCount();p++){
                gia=Integer.parseInt(tbl_data.getValueAt(p, 6).toString())*Integer.parseInt(tbl_data.getValueAt(p, 3).toString());
                thanhtien=thanhtien+gia;
            }
            int tongcong=thanhtien+thanhtien*Integer.parseInt(txt_chietkhau.getText())/100;
            Locale localeVN = new Locale("vi", "VN");
            NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
            String thanhtien1 = currencyVN.format(thanhtien);
            String tongcong1 = currencyVN.format(tongcong);
            
            lbchietkhau.setText(txt_chietkhau.getText()+" %");
            lbthanhtien.setText(thanhtien1);
            lbtongcong.setText(tongcong1);
        }
        
        
    }//GEN-LAST:event_jPanel2MouseClicked
    private void reset(){
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        model.setRowCount(0);
        txt_giaban.setText("");
        txt_gianhap.setText("");
        txt_mahang.setText("");
        txt_tenhang.setText("");
        cb_dvt.setSelectedIndex(0);
        cb_manv.setSelectedIndex(0);
        cb_nhacc.setSelectedIndex(0);
        cb_tenlhang.setSelectedIndex(0);
        ngayhientai();
        sluong.setValue(0);
        txt_chietkhau.setText("0");
        txt_datra.setText("0");
        lbchietkhau.setText("");
        lbthanhtien.setText("");
        lbtongcong.setText("");
        default_manv();
    }
    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        DefaultTableModel model = (DefaultTableModel)tbl_data.getModel();
        if(tbl_data.getSelectedRow() >= 0){
            model.removeRow(tbl_data.getSelectedRow());
        } else{
            JOptionPane.showMessageDialog(this, "Không thể xóa.");
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void hoadonN(){
        Nv_nhaphang nhaphang = new Nv_nhaphang();
     
        Date date = cbngaynhap.getDate();
        String dateInput = new SimpleDateFormat("yyyy-MM-dd").format(date);
        boolean isNumeric = true;
        
        try {
            int num = Integer.parseInt(txt_chietkhau.getText());
            if(num>0 && num <=100){
                isNumeric = true;
            }
            isNumeric = true;

         } catch (NumberFormatException e) {
            isNumeric = false;
        }
        String s = new String();
        int j;
        for(j=0;j<=cb_nhacc.getSelectedItem().toString().length();j++){//lấy mã của DVT
                    s=cb_nhacc.getSelectedItem().toString().substring(j,j+1);
                    if(s.equals(",")) break;                                             
            }
        if (isNumeric) {     
            int thanhtien=0,gia=0;
            for(int p=0;p<tbl_data.getRowCount();p++){
                gia=Integer.parseInt(tbl_data.getValueAt(p, 6).toString())*Integer.parseInt(tbl_data.getValueAt(p, 3).toString());
                thanhtien=thanhtien+gia;
            }
            int tongcong=thanhtien+thanhtien*Integer.parseInt(txt_chietkhau.getText())/100;
            nhaphang.setNgay_nhap(dateInput);
            nhaphang.setMa_NV(cb_manv.getSelectedItem().toString());
            nhaphang.setMa_NCC(cb_nhacc.getSelectedItem().toString().substring(0,j));
            nhaphang.setChietkhau(Integer.parseInt(txt_chietkhau.getText()));
            nhaphang.setDa_tra(Integer.parseInt(txt_datra.getText()));
            nhaphang.setThanhtiennhap(tongcong);
            DAOnhaphang.ThemHoadonN(nhaphang); 

            JOptionPane.showMessageDialog(this, "Thêm mới Hóa đơn thành công!");//đưa ra thông báo khi thực hiện thành công
        }
        else{
            JOptionPane.showMessageDialog(this, "% Chiết khấu phải lớn hơn 0 và nhỏ hơn 100!", "Thông báo", JOptionPane.WARNING_MESSAGE); 
        }
    }
    private void themhang(){
        Nv_nhaphang nhaphang = new Nv_nhaphang();

        int j,k;
        String s=new String();
        for (int i = 0; i < tbl_data.getRowCount() ; i++) {
            
            boolean isNumeric = true;          
            if (isNumeric) { 
                nhaphang.setMa_hang(tbl_data.getValueAt(i, 0).toString());
                nhaphang.setTen_hang(tbl_data.getValueAt(i, 1).toString());

                nhaphang.setMa_loaihang(tbl_data.getValueAt(i, 5).toString());
                nhaphang.setMa_dvt(Integer.parseInt(tbl_data.getValueAt(i, 4).toString()));
                             
                DAOnhaphang.ThemHang(nhaphang);
            }
        }
    }
    private void ctietN(){
        Nv_nhaphang nhaphang = new Nv_nhaphang();
        Dm_khohang kho = new Dm_khohang();
        boolean isNumeric = true;
        for (int i = 0; i < tbl_data.getRowCount() ; i++) {
            try {
                int num = Integer.parseInt(tbl_data.getValueAt(i, 6).toString());
                int num2=Integer.parseInt(tbl_data.getValueAt(i, 3).toString());
                int num3=Integer.parseInt(tbl_data.getValueAt(i, 2).toString());
                isNumeric = true;

             } catch (NumberFormatException e) {
                isNumeric = false;
            }
            if (isNumeric) {
                int j;
                String s = new String();
                for(j = 0;j <= cb_makho.getSelectedItem().toString().length(); j++){//lấy mã của kho hàng
                    s=cb_makho.getSelectedItem().toString().substring(j,j+1);
                    if(s.equals(",")) break;                                             
                }
                try {
                    Connection conn = MySQLConnUtils.getMySQLConnection();
                    PreparedStatement stm = conn.prepareStatement("SELECT * FROM hoadonnhap ORDER BY hoadonnhap.Ma_HDN DESC LIMIT 0,1");
                    ResultSet rs = stm.executeQuery();

                    while (rs.next()) {
                        nhaphang.setMa_HDN(rs.getInt("Ma_HDN"));
                    }
                } catch (Exception e){
                    
                }
                nhaphang.setSoluongN(Integer.parseInt(tbl_data.getValueAt(i, 6).toString()));
                nhaphang.setDongiaN(Integer.parseInt(tbl_data.getValueAt(i, 3).toString()));
                nhaphang.setGiaban(Integer.parseInt(tbl_data.getValueAt(i, 2).toString()));
                nhaphang.setMa_hang(tbl_data.getValueAt(i, 0).toString());               
                
                kho.setMa_khohang(cb_makho.getSelectedItem().toString().substring(0,j));
                kho.setMa_hang(tbl_data.getValueAt(i, 0).toString());
                kho.setSL_tonkho(Integer.parseInt(tbl_data.getValueAt(i, 6).toString()));
                
                DAOkhohang.ThemCTkho(kho);
                DAOnhaphang.ThemCTnhap(nhaphang); 
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Giá tiền phải nhập số!", "Thông báo", JOptionPane.WARNING_MESSAGE); 
            }
        }
    }
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        hoadonN();
        themhang();
        ctietN();
        reset();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        new Frame.In_hoadonnhaphang().setVisible(true);
    }//GEN-LAST:event_jPanel13MouseClicked

    private void cb_manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_manvActionPerformed
        default_manv();
    }//GEN-LAST:event_cb_manvActionPerformed
    private void default_manv(){
        try {
            dbConnection = MySQLConnUtils.getMySQLConnection();
            statement = dbConnection.createStatement();
            String sql = "SELECT * FROM nhanvien WHERE Ma_NV='"+cb_manv.getSelectedItem().toString()+"'";
            
            ResultSet rs = statement.executeQuery(sql);
            while ((rs != null) && (rs.next())) {
                txt_tennv.setText(rs.getString("Hoten"));
            }
        }
        catch(Exception e ){
            JOptionPane.showMessageDialog(null, e);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_dvt;
    private javax.swing.JComboBox cb_makho;
    private javax.swing.JComboBox cb_manv;
    private javax.swing.JComboBox cb_nhacc;
    private javax.swing.JComboBox cb_tenlhang;
    private com.toedter.calendar.JDateChooser cbngaynhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbchietkhau;
    private javax.swing.JLabel lbthanhtien;
    private javax.swing.JLabel lbtongcong;
    private javax.swing.JSpinner sluong;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTextField txt_chietkhau;
    private javax.swing.JTextField txt_datra;
    private javax.swing.JTextField txt_giaban;
    private javax.swing.JTextField txt_gianhap;
    private javax.swing.JTextField txt_mahang;
    private javax.swing.JTextField txt_tenhang;
    private javax.swing.JTextField txt_tennv;
    // End of variables declaration//GEN-END:variables
}
